# Generated by Django 4.2 on 2023-05-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoarticle',
            name='completion_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='완료 날짜'),
        ),
        migrations.AlterField(
            model_name='todoarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='todoarticle',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='완료 여부'),
        ),
        migrations.AlterField(
            model_name='todoarticle',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='할일 제목'),
        ),
        migrations.AlterField(
            model_name='todoarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 일시'),
        ),
    ]
